services:
  mkdocs:
    image: squidfunk/mkdocs-material:9.6
    ports:
      - 8000:8000
    volumes:
      - ./docs:/docs
      - ./.github/mkdocs/docs:/default
      - ./.github/mkdocs:/.github/mkdocs
    entrypoint:
      - sh
      - -c
    command:
      - >-
        cp -rn /default/* /docs/ &&
        pip install -r /.github/mkdocs/requirements.txt &&
        mkdocs serve --config-file /.github/mkdocs/mkdocs.yml
        --dev-addr=0.0.0.0:8000
