site_name: SciCat Documentation
docs_dir: ../../docs

nav: 
  - Home: index.md
  - About:
      - about/index.md

theme:
  name: material
  palette:
    primary: indigo
    accent: light-blue
  logo: .assets/SciCat-logo-icon.png
  features:
   - instant

plugins:
  - search
  # - glightbox
  # - section-index
