site_name: SciCat Documentation
docs_dir: ../../docs

theme:
  name: material
  palette:
    primary: indigo
    accent: light-blue
  logo: assets/SciCat-logo-icon.png
  features:
   - instant

# If you are using awesome pages please comment out this section
nav:
  - Home: index.md
  - About: about/index.md

extra:
  version:
    provider: mike

plugins:
  - search
  - glightbox
  # If you want to use awesome-pages uncomment this plugin and delete the "nav" section.
  # - awesome-pages:
  #     collapse_single_pages: true
  - mike
  - section-index

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - tables
  - pymdownx.extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - css/custom.css
# hooks:
#   - relative_to.py
